-- phpMyAdmin SQL Dump
-- version 4.9.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Dec 17, 2020 at 02:54 PM
-- Server version: 5.6.49-cll-lve
-- PHP Version: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `aauwnm608vierl`
--

-- --------------------------------------------------------

--
-- Table structure for table `track_moods`
--

CREATE TABLE `track_moods` (
  `id` int(11) NOT NULL,
  `user_id` varchar(11) NOT NULL,
  `mood` varchar(64) NOT NULL,
  `icon` varchar(128) NOT NULL,
  `week` varchar(64) NOT NULL,
  `date` varchar(64) NOT NULL,
  `location` varchar(64) NOT NULL,
  `title` varchar(64) NOT NULL,
  `img` varchar(256) NOT NULL,
  `description` text NOT NULL,
  `date_create` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `track_moods`
--

INSERT INTO `track_moods` (`id`, `user_id`, `mood`, `icon`, `week`, `date`, `location`, `title`, `img`, `description`, `date_create`) VALUES
(50, '2', 'normal', 'img/normal.png', 'Thursday', '11-07-2020', '845 Melba Court', 'cillum incididunt est qui', 'https://via.placeholder.com/998/fff/?text=MOOD', 'Amet laborum qui commodo pariatur fugiat culpa occaecat aute ipsum minim cillum. Excepteur eiusmod aliqua est elit exercitation. Est excepteur cupidatat amet quis irure exercitation sunt id consequat eu culpa id sunt.\r\n\nIpsum cupidatat aliqua officia et minim est. Exercitation sint fugiat irure minim irure officia dolore deserunt aliqua magna est. Labore non non consectetur magna velit ex excepteur. Irure fugiat elit id occaecat magna adipisicing laboris laboris esse.\r\n\n', '2020-03-14 10:47:11'),
(49, '7', 'angry', 'img/angry.png', 'Wednesday', '07-31-2020', '725 Louis Place', 'ad ut consequat cillum', 'https://via.placeholder.com/960/fff/?text=MOOD', 'Lorem ipsum eiusmod nostrud magna aliquip sit duis quis minim nisi aliqua. Incididunt reprehenderit dolor minim consequat minim qui est quis minim officia aliquip. Amet duis eu do consectetur dolor mollit amet velit ipsum laboris exercitation et. Duis do Lorem anim velit nisi Lorem irure id dolor sunt. Sint amet aliquip voluptate velit veniam qui aliqua ad eu incididunt nulla aute culpa. Irure aute eu sit irure deserunt et consequat.\r\n\nQuis voluptate dolor minim fugiat nostrud sit. Do id incididunt consequat voluptate mollit commodo aute proident pariatur quis in voluptate. Pariatur exercitation incididunt qui nulla sint enim qui adipisicing voluptate ex quis est tempor. Deserunt et magna nulla proident veniam dolor enim laboris minim ipsum pariatur pariatur. Aliquip Lorem sunt ipsum occaecat nostrud et sit amet veniam consectetur veniam occaecat. Labore nisi adipisicing cupidatat nisi amet.\r\n\n', '2020-06-17 01:05:03'),
(48, '10', 'smile', 'img/smile.png', 'Sunday', '02-29-2020', '402 Jerome Avenue', 'cupidatat pariatur commodo ut', 'https://via.placeholder.com/935/fff/?text=MOOD', 'Ut sit amet aliquip ullamco consequat fugiat incididunt nisi eu nulla Lorem proident voluptate excepteur. Cupidatat laborum mollit id in officia qui exercitation eiusmod magna id ut cupidatat reprehenderit. Qui cupidatat non non culpa cupidatat culpa excepteur. Sint culpa nisi ad aliquip magna ad ullamco minim aute aliquip. Ut aliqua ullamco deserunt occaecat commodo magna officia sint amet Lorem culpa sint non minim. Dolore ut laboris elit eiusmod qui. Magna minim consectetur Lorem proident laboris.\r\n\nAute magna cupidatat reprehenderit esse fugiat duis nulla nostrud irure esse id aute cupidatat. Adipisicing duis eu pariatur aute est sunt irure duis mollit fugiat. Ex quis id nostrud aliqua minim anim nisi nisi veniam amet ipsum officia ipsum. Nisi consectetur qui officia minim id ipsum do mollit. Excepteur irure amet duis voluptate. Mollit minim qui excepteur consequat. Culpa ipsum nisi aliquip ex voluptate quis ad adipisicing.\r\n\n', '2020-01-08 07:19:56'),
(47, '10', 'normal', 'img/normal.png', 'Monday', '07-21-2020', '502 Greenwood Avenue', 'exercitation nulla pariatur esse', 'https://via.placeholder.com/705/fff/?text=MOOD', 'Laboris nostrud consectetur voluptate aliquip nulla cupidatat. Laboris ullamco excepteur amet tempor qui dolor non. Ut veniam occaecat sint irure Lorem nulla dolor et ea occaecat cupidatat. Laboris ex ullamco eiusmod non. Consectetur voluptate laboris est nostrud proident aliquip magna laboris reprehenderit incididunt reprehenderit consequat enim reprehenderit.\r\n\nProident in veniam laborum excepteur aliqua non laboris adipisicing aliquip duis consectetur labore fugiat. Aliquip velit anim ullamco est dolor minim eu qui. Culpa amet laboris Lorem irure ut Lorem eiusmod laboris eiusmod esse proident culpa consectetur. Magna exercitation irure Lorem officia tempor sunt quis esse aliqua voluptate ullamco labore laboris ipsum.\r\n\n', '2020-12-05 12:06:54'),
(46, '4', 'sad', 'img/sad.png', 'Friiday', '04-03-2020', '171 Colin Place', 'labore velit officia consequat', 'https://via.placeholder.com/731/fff/?text=MOOD', 'Commodo minim labore voluptate quis et eiusmod eiusmod. Culpa magna laborum tempor excepteur excepteur nostrud laborum cillum. Do do velit qui culpa adipisicing elit. Laboris mollit laboris adipisicing laborum fugiat Lorem culpa esse duis cupidatat veniam amet labore est. Eiusmod reprehenderit mollit dolore veniam consectetur ut.\r\n\nAliqua culpa anim aliquip excepteur velit excepteur mollit amet occaecat ut officia aliquip. Eiusmod fugiat irure voluptate deserunt ea labore sunt. Sunt ipsum occaecat enim eiusmod cupidatat quis.\r\n\n', '2020-01-01 04:51:50'),
(45, '5', 'sad', 'img/sad.png', 'Friiday', '04-24-2020', '457 Campus Place', 'laboris sunt consequat culpa', 'https://via.placeholder.com/950/fff/?text=MOOD', 'Sint cillum deserunt tempor sunt qui voluptate ullamco dolore et cupidatat et laborum cillum. Adipisicing commodo minim id aliqua ullamco do velit veniam eiusmod non velit do. Elit aute sunt enim deserunt non sunt.\r\n\nNostrud nulla anim Lorem culpa duis. Consectetur est mollit irure eu eiusmod enim do deserunt esse cillum proident voluptate ullamco nostrud. Anim nisi dolore dolore sit fugiat. Aliqua ea voluptate magna veniam. Elit enim consectetur commodo labore non ullamco nostrud dolore ex magna pariatur proident sit eiusmod. Irure non occaecat sit eu. Nostrud magna fugiat non veniam sit sit commodo anim deserunt qui labore.\r\n\n', '2020-08-22 03:57:51'),
(44, '5', 'happy', 'img/happy.png', 'Friiday', '07-14-2020', '282 Hemlock Street', 'elit exercitation enim laborum', 'https://via.placeholder.com/808/fff/?text=MOOD', 'Consequat duis aliqua nostrud elit sunt. Amet elit enim ad aute elit voluptate aute excepteur culpa tempor eiusmod duis ad. Id elit anim commodo in nulla excepteur nostrud velit exercitation ipsum enim in veniam nulla. Est occaecat culpa proident cupidatat tempor eu sunt do et labore. Amet laboris Lorem est consequat aliquip adipisicing. Esse laboris anim consectetur do irure.\r\n\nMagna aliquip sint reprehenderit enim laborum. Proident ea sint reprehenderit quis aliqua nisi ex fugiat do occaecat incididunt non. Consectetur id amet aliqua irure fugiat amet incididunt minim ea labore culpa sunt officia duis. Culpa culpa et quis esse anim id sint id duis mollit et.\r\n\n', '2020-08-11 11:49:45'),
(43, '2', 'happy', 'img/happy.png', 'Tuesday', '11-26-2020', '376 Elm Place', 'minim voluptate sunt dolor', 'https://via.placeholder.com/896/fff/?text=MOOD', 'Cupidatat enim mollit excepteur ex voluptate elit nisi aliqua eu ad. Aliquip laborum id incididunt consectetur dolore veniam veniam. Ad fugiat dolore ea dolore occaecat et. Laborum incididunt commodo consectetur eiusmod cillum non reprehenderit Lorem exercitation. Quis aliqua cupidatat elit magna dolor consectetur tempor Lorem irure.\r\n\nEa dolore fugiat anim ea dolor quis non est eiusmod occaecat anim. Excepteur ea deserunt aliquip pariatur aliquip labore. Ad enim cupidatat laborum deserunt aliqua et eu magna. Excepteur aliqua sit mollit aliqua Lorem aute nisi nulla ea nisi. Veniam mollit dolore nulla magna aliqua enim pariatur deserunt exercitation anim quis ipsum nisi. Sunt culpa nisi ex irure do Lorem voluptate quis et velit sunt occaecat.\r\n\n', '2020-05-21 03:43:09'),
(42, '6', 'smile', 'img/smile.png', 'Saturday', '01-22-2020', '533 Banner Avenue', 'culpa anim deserunt adipisicing', 'https://via.placeholder.com/792/fff/?text=MOOD', 'Eiusmod cupidatat officia Lorem consequat esse non sunt exercitation ea tempor. Id cillum ex pariatur enim eu do exercitation anim elit in irure magna elit esse. Ipsum do irure velit fugiat ea proident officia esse. Exercitation mollit sint magna minim exercitation ea eiusmod consequat nostrud elit. Magna voluptate tempor sunt deserunt tempor. Reprehenderit deserunt nostrud esse adipisicing nisi laboris et sit veniam esse ipsum occaecat.\r\n\nId occaecat pariatur et nisi mollit sit Lorem. Culpa laborum ullamco laborum sunt veniam deserunt laboris do occaecat eiusmod. Sit veniam eiusmod adipisicing eu ipsum pariatur fugiat aliqua aute amet dolor enim. Labore enim aute duis cupidatat amet quis aliqua quis aliqua. Reprehenderit proident voluptate laboris sit.\r\n\n', '2020-10-14 12:44:39'),
(41, '9', 'angry', 'img/angry.png', 'Saturday', '05-30-2020', '270 Ross Street', 'consequat ut minim amet', 'https://via.placeholder.com/888/fff/?text=MOOD', 'Officia laborum exercitation proident eu amet mollit voluptate ea. Consequat qui irure dolore excepteur sint sit in qui. Officia dolor nostrud voluptate anim mollit fugiat mollit reprehenderit ut cupidatat incididunt qui.\r\n\nCommodo occaecat ex qui quis cillum occaecat aute irure aute eu irure minim tempor qui. Lorem id sint laboris ullamco ex reprehenderit officia velit velit consequat magna dolore officia ipsum. Id fugiat proident commodo reprehenderit officia nostrud labore tempor culpa cupidatat quis. Non dolore ad cillum nostrud labore. Sunt duis est proident reprehenderit pariatur nulla exercitation anim mollit sint mollit.\r\n\n', '2020-01-03 04:55:57'),
(40, '10', 'sad', 'img/sad.png', 'Sunday', '07-22-2020', '466 Highlawn Avenue', 'irure consectetur nostrud reprehenderit', 'https://via.placeholder.com/883/fff/?text=MOOD', 'Nostrud ea elit laboris irure est labore incididunt ullamco consequat Lorem cupidatat laborum. Et exercitation eu mollit nulla voluptate id nulla do in cillum. Ad id irure fugiat exercitation do nostrud ad consequat aute mollit quis commodo. Sint magna culpa occaecat incididunt aliquip. Eiusmod qui aliqua amet mollit. Ea excepteur ad minim consectetur pariatur.\r\n\nConsequat sit tempor proident ut consectetur cupidatat pariatur. Officia officia eiusmod reprehenderit in incididunt incididunt. Voluptate amet nostrud esse duis laborum commodo aute commodo Lorem do. Ea ipsum Lorem sunt ea qui. Commodo mollit elit anim velit proident. Non id irure amet quis commodo eiusmod.\r\n\n', '2020-11-18 02:48:35'),
(39, '5', 'happy', 'img/happy.png', 'Monday', '04-03-2020', '427 Durland Place', 'eu Lorem non et', 'https://via.placeholder.com/743/fff/?text=MOOD', 'Nulla deserunt et deserunt in laborum officia sit fugiat et. Qui dolor esse laboris cillum laboris fugiat eiusmod officia dolor commodo elit. Elit et commodo consequat deserunt elit cillum veniam aute ex sint nostrud commodo. Irure labore labore aliquip in velit deserunt dolore commodo non elit laboris Lorem in.\r\n\nNostrud proident anim commodo sit veniam ut sint nulla labore aliqua dolor incididunt nisi. Reprehenderit ex qui labore nulla aute voluptate ipsum cupidatat. Sunt velit est quis dolor. Nisi nostrud non tempor ex esse nostrud laboris sint quis eu officia ipsum.\r\n\n', '2020-04-29 05:03:08'),
(38, '3', 'angry', 'img/angry.png', 'Tuesday', '02-07-2020', '551 Micieli Place', 'cillum irure commodo reprehenderit', 'https://via.placeholder.com/711/fff/?text=MOOD', 'Minim labore magna adipisicing deserunt. Exercitation est dolor non labore do velit consectetur voluptate laboris. Nisi eu amet dolore laborum ipsum dolore Lorem dolore proident nisi esse. Mollit et in velit tempor nostrud in veniam esse est sunt Lorem dolor. Id esse sint laborum cupidatat.\r\n\nDuis qui ex Lorem veniam consectetur ullamco. Anim aliquip qui et ut cupidatat proident. Dolor laboris aute magna nisi est. Excepteur quis dolor velit dolore tempor officia quis pariatur irure ex. Incididunt labore ad occaecat ea Lorem officia fugiat deserunt nostrud do et. Deserunt ut cillum laborum Lorem minim culpa voluptate enim excepteur ut ea. Deserunt eiusmod labore dolore amet in cillum anim minim do aliqua id fugiat dolor.\r\n\n', '2020-04-27 02:42:12'),
(37, '7', 'normal', 'img/normal.png', 'Wednesday', '07-01-2020', '993 Albemarle Road', 'officia ullamco do in', 'https://via.placeholder.com/905/fff/?text=MOOD', 'Cupidatat proident deserunt exercitation aliquip ut culpa dolor et elit magna. In aliquip cillum ut velit cillum voluptate et dolor Lorem ut qui esse. Voluptate sunt voluptate nulla reprehenderit quis laborum ut ea. Sunt elit ipsum culpa aliquip exercitation amet officia pariatur ea. Culpa duis irure quis occaecat ex fugiat veniam.\r\n\nUllamco culpa veniam do sit magna cupidatat elit aliqua id nulla enim et. Esse elit aute quis exercitation labore in culpa officia consequat dolore exercitation ea anim voluptate. Culpa laborum magna pariatur cupidatat aliquip.\r\n\n', '2020-06-09 01:29:26'),
(36, '2', 'sad', 'img/sad.png', 'Monday', '02-02-2020', '282 Leonard Street', 'laborum cillum pariatur labore', 'https://via.placeholder.com/839/fff/?text=MOOD', 'Culpa commodo proident esse officia qui fugiat non esse incididunt mollit ullamco reprehenderit. Aliquip est aliquip quis nisi voluptate exercitation nulla quis proident aliqua proident culpa. Cillum quis sit qui consequat dolor Lorem sit cupidatat excepteur aliqua excepteur pariatur. Tempor mollit minim officia minim excepteur. Irure eiusmod minim proident nisi elit sit veniam magna voluptate reprehenderit non.\r\n\nLaboris labore est nostrud et qui amet culpa qui magna culpa occaecat laborum sint. Ullamco nostrud aliquip aliquip ad reprehenderit. Aliqua ad proident exercitation non. Cillum do duis reprehenderit aute dolor elit occaecat ad exercitation eiusmod sint id consectetur elit.\r\n\n', '2020-08-31 01:04:14'),
(35, '8', 'normal', 'img/normal.png', 'Monday', '09-16-2020', '862 Williams Court', 'amet proident in mollit', 'https://via.placeholder.com/863/fff/?text=MOOD', 'Labore consectetur cupidatat magna incididunt officia dolore cupidatat minim eu nostrud consectetur est. Aliqua magna cupidatat deserunt ipsum occaecat. Magna in mollit officia excepteur eu voluptate. Fugiat sunt deserunt esse qui eu dolore laboris esse duis. Voluptate pariatur fugiat cupidatat ad irure aliqua amet sit nulla ut non.\r\n\nFugiat magna Lorem culpa excepteur eiusmod proident deserunt est aute et et. Aliquip nulla minim culpa adipisicing reprehenderit commodo reprehenderit non ea laborum est incididunt nostrud. Labore fugiat sit ad cupidatat elit nisi anim veniam velit velit deserunt in pariatur Lorem. Officia veniam culpa ex adipisicing anim ad ipsum quis sint in. In non ex proident sint ex aute ex occaecat sit laboris eiusmod voluptate. Voluptate excepteur tempor excepteur consectetur cillum reprehenderit eiusmod magna elit sunt. Tempor consequat exercitation est enim adipisicing excepteur excepteur.\r\n\n', '2020-09-12 06:46:20'),
(34, '7', 'normal', 'img/normal.png', 'Sunday', '07-22-2020', '574 Columbia Street', 'minim est ad eu', 'https://via.placeholder.com/726/fff/?text=MOOD', 'Occaecat cupidatat est reprehenderit amet laborum excepteur cillum sint dolore. Minim consequat nulla Lorem sint. In in duis dolore officia ad irure minim non irure officia. Ad sit labore amet sunt et dolor in sunt cillum laboris dolore duis.\r\n\nConsectetur aliqua labore in esse velit nostrud. Esse et ipsum aute id. Laborum nostrud pariatur est cillum. Ad consequat cillum laborum enim commodo nulla.\r\n\n', '2020-07-09 01:54:24'),
(33, '10', 'normal', 'img/normal.png', 'Friiday', '08-16-2020', '614 Dumont Avenue', 'cupidatat veniam sit culpa', 'https://via.placeholder.com/790/fff/?text=MOOD', 'Cillum ipsum minim duis aute dolor culpa sit Lorem esse. Elit ex voluptate ut aliqua amet excepteur duis magna in laborum aliqua ex nulla sit. Mollit esse laboris quis consectetur eiusmod velit ex quis cillum nulla veniam esse.\r\n\nExercitation et aliquip aliquip cupidatat ullamco velit occaecat cillum deserunt elit laboris voluptate consectetur. Est proident elit ullamco nisi irure. Sint sunt do consectetur ex cillum officia mollit et ea exercitation laborum occaecat nulla. Enim tempor laboris consequat et deserunt do et. Exercitation irure tempor anim deserunt ad ex ex pariatur elit sit deserunt sint do veniam.\r\n\n', '2020-11-16 10:52:02'),
(32, '9', 'angry', 'img/angry.png', 'Saturday', '04-19-2020', '730 Surf Avenue', 'esse sunt commodo eiusmod', 'https://via.placeholder.com/841/fff/?text=MOOD', 'Sunt minim commodo fugiat id commodo quis magna consectetur ea aliquip Lorem dolor. Fugiat mollit voluptate do minim cillum tempor elit enim pariatur. Ut incididunt aute deserunt magna officia ut do ex. Mollit sit proident qui aliqua ullamco voluptate adipisicing excepteur qui proident reprehenderit. Sint exercitation enim non culpa ipsum consequat duis deserunt pariatur sunt. Anim reprehenderit enim pariatur labore deserunt nulla nisi veniam veniam tempor.\r\n\nDo labore esse magna pariatur cillum enim tempor. In eu officia eiusmod ex enim amet mollit laborum proident. Eu deserunt ut est sint aliqua nostrud.\r\n\n', '2020-09-04 03:52:00'),
(31, '1', 'smile', 'img/smile.png', 'Monday', '05-31-2020', '482 Brighton Avenue', 'reprehenderit incididunt ad eu', 'https://via.placeholder.com/906/fff/?text=MOOD', 'Aute labore esse officia consectetur excepteur sint incididunt voluptate non excepteur magna magna ullamco elit. Et cupidatat esse pariatur aliqua Lorem ea mollit sint. Ipsum laboris ipsum cillum nulla. Nisi in amet quis aute id voluptate exercitation dolore aliquip id consectetur. Consectetur quis anim id qui voluptate ullamco voluptate quis in ut sit pariatur. Velit esse non velit in proident. Magna velit adipisicing labore magna exercitation sunt.\r\n\nCillum excepteur tempor id amet elit consectetur magna veniam aliquip pariatur ut aliqua labore. Cillum esse ex consequat culpa culpa nulla laborum dolor ad. Nulla elit occaecat ea eu eu anim ut sit aliqua duis laboris ut exercitation nisi. Esse labore Lorem magna commodo Lorem occaecat. Et ut deserunt tempor id consequat exercitation tempor reprehenderit nulla. Commodo esse reprehenderit commodo Lorem ipsum voluptate ipsum aute sint qui ex ipsum.\r\n\n', '2020-07-12 02:02:39'),
(30, '5', 'normal', 'img/normal.png', 'Friiday', '07-03-2020', '535 Franklin Avenue', 'esse mollit reprehenderit dolor', 'https://via.placeholder.com/797/fff/?text=MOOD', 'Velit tempor incididunt sunt amet commodo enim ut nisi veniam excepteur. Ea pariatur dolor quis eiusmod in aliqua exercitation do ea. Veniam ad proident nisi eiusmod aliqua ut velit ut occaecat nulla enim in. Commodo veniam aliquip Lorem fugiat laboris tempor ut culpa duis laboris laborum dolor velit et. Ea consectetur tempor sit cupidatat aute mollit exercitation id quis cupidatat adipisicing Lorem.\r\n\nMinim tempor culpa tempor duis tempor enim nisi laborum velit quis irure. Est elit ipsum consequat voluptate duis ut adipisicing laborum minim excepteur eu voluptate deserunt id. Eiusmod sit dolore duis est aliqua ipsum consectetur laborum in nostrud voluptate. Deserunt deserunt cillum aliquip qui in incididunt cillum ex sit.\r\n\n', '2020-09-28 02:39:20'),
(29, '2', 'smile', 'img/smile.png', 'Thursday', '03-06-2020', '408 Gold Street', 'quis Lorem elit veniam', 'https://via.placeholder.com/994/fff/?text=MOOD', 'Fugiat ipsum est ut ut occaecat nisi. Ea sunt ad pariatur consectetur occaecat cupidatat laboris ullamco et amet enim reprehenderit. Aute quis cupidatat enim labore culpa ea. Adipisicing officia nulla excepteur anim tempor et exercitation exercitation proident. Officia eu in consectetur sunt id magna duis excepteur non reprehenderit eiusmod cupidatat consequat. Occaecat magna officia voluptate esse adipisicing. Nulla consectetur enim laborum sit fugiat ex commodo ullamco proident consectetur officia.\r\n\nEsse eiusmod et ad qui do. Ipsum occaecat ex est qui nostrud veniam laborum sit nisi qui qui dolor enim. Incididunt elit excepteur sint sint do sit. Deserunt est incididunt sunt qui exercitation eu.\r\n\n', '2020-08-30 05:10:26'),
(28, '3', 'normal', 'img/normal.png', 'Sunday', '07-01-2020', '241 Brown Street', 'mollit ullamco sint incididunt', 'https://via.placeholder.com/957/fff/?text=MOOD', 'Aliqua veniam laborum commodo ipsum. Mollit qui nostrud culpa esse nisi excepteur enim laborum enim proident. Ad laborum Lorem do in ex cillum nostrud ex sit adipisicing. Qui id ad enim magna nisi deserunt aliquip reprehenderit aute Lorem ullamco eu labore adipisicing.\r\n\nEst ipsum culpa cupidatat ea ad amet. Ipsum voluptate dolor nulla labore aliqua. Adipisicing nisi do nulla non ex non non dolor amet dolor eiusmod magna voluptate aute. Occaecat eiusmod pariatur nostrud ex magna dolore est. Sint exercitation do magna nisi cillum fugiat voluptate ad occaecat pariatur ipsum. Nisi sint mollit minim nostrud irure adipisicing id quis mollit Lorem. Nostrud qui et pariatur proident esse dolor labore officia esse ut laboris est mollit enim.\r\n\n', '2020-10-10 05:21:41'),
(27, '8', 'happy', 'img/happy.png', 'Wednesday', '06-01-2020', '796 Bond Street', 'irure excepteur incididunt aliqua', 'https://via.placeholder.com/832/fff/?text=MOOD', 'Veniam ea sunt ut reprehenderit nisi consectetur. Laboris pariatur tempor aliquip quis occaecat eiusmod ad consequat consectetur incididunt culpa exercitation sit aute. Mollit esse nostrud exercitation sunt in eu elit dolore. Proident ea esse consequat nulla ut commodo sit minim velit minim ut adipisicing anim.\r\n\nMagna magna culpa aliquip proident ea aliquip aute officia anim anim nostrud occaecat occaecat. Ut adipisicing pariatur culpa dolore laborum incididunt Lorem. Ea aute deserunt fugiat veniam sunt incididunt.\r\n\n', '2020-09-02 11:11:03'),
(26, '2', 'sad', 'img/sad.png', 'Saturday', '04-28-2020', '877 Vanderbilt Avenue', 'enim excepteur consectetur ex', 'https://via.placeholder.com/734/fff/?text=MOOD', 'Nulla qui voluptate ex commodo minim labore fugiat. Non ad voluptate ad sint cupidatat ad ad. In adipisicing commodo adipisicing Lorem reprehenderit id cillum magna qui. Culpa quis ullamco occaecat do. Quis eiusmod quis in anim sit voluptate officia ullamco esse laborum id do sunt non.\r\n\nProident quis adipisicing magna qui consequat ad est. Ut occaecat fugiat deserunt nisi tempor nisi laboris et qui duis est. Incididunt quis do ut ut occaecat veniam sunt proident. Cupidatat reprehenderit tempor elit adipisicing ullamco cillum eu in ullamco sit labore consequat. Veniam cillum laboris velit eu labore adipisicing voluptate in est enim deserunt. Commodo labore elit esse tempor exercitation dolor quis ut deserunt ex labore eiusmod. Labore eu ut aliqua laboris esse cillum cillum proident officia ad.\r\n\n', '2020-05-12 03:36:53');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `track_moods`
--
ALTER TABLE `track_moods`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `track_moods`
--
ALTER TABLE `track_moods`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
